export const skills = {
  heading: "Skills",
  quote: "Hire for Character, Train for skills! - Michael Josephson ",
  skillCategories: {
    "Tech Skills": [
      "Java",
      "Python",
      "Spring",
      "Spring Boot",
      "Spring Microservices",
      "JavaScript",
      "ReactJS",
      "React Native",
      "Redux",
      "C++",
      "C#",
      "C",
      "HTML",
      "CSS",
      "jQuery",
      "Bootstrap",
      "Git",
      "GitHub",
      "SQL",
      "PostgreSQL",
      "MongoDB",
    ],
    "Industry Knowledge": [
      "Software",
      "Web Content",
      "Frontend",
      "Backend",
      "Design",
      "Web",
      "Android",
    ],
    "Interpersonal Skills": [
      "Communication",
      "Teaching",
      "Time Management",
      "Leadership",
      "Management",
      "Adaptability",
    ],
  },
};
